<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2fhjdct\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2fhjdct/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container2fhjdct.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container2fhjdct\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container2fhjdct\appDevDebugProjectContainer(array(
    'container.build_hash' => '2fhjdct',
    'container.build_id' => 'a7a0a11f',
    'container.build_time' => 1539785918,
), __DIR__.\DIRECTORY_SEPARATOR.'Container2fhjdct');
