<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0ol0cwc\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0ol0cwc/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container0ol0cwc.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container0ol0cwc\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container0ol0cwc\appDevDebugProjectContainer(array(
    'container.build_hash' => '0ol0cwc',
    'container.build_id' => 'cf713d8a',
    'container.build_time' => 1540291942,
), __DIR__.\DIRECTORY_SEPARATOR.'Container0ol0cwc');
